---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    team: ${team_name}
  requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values: ${zones}
    - key: karpenter.sh/capacity-type
      operator: In
      values: ${capacity_types}
  limits:
    resources:
      cpu: ${cpu_limit}
      memory: ${memory_limit}
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${cluster_name}  
    securityGroupSelector:
      karpenter.sh/discovery: ${cluster_name} 
  ttlSecondsAfterEmpty: ${ttl_seconds_after_empty}
