---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    team: dev-team
  requirements:
    # - key: node.kubernetes.io/instance-type
    #   operator: In
    #   values: [t3a.large, t3.medium]           # Instances type/size
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ap-south-1a, ap-south-1b, ap-south-1c] #Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-muse-elevar-eks-dev
  ttlSecondsAfterEmpty: 30