apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  instanceProfile: ${instance_profile}
  userData: |
    echo "Custom User Data"    
  tags:
    team: team-a
    app: team-a-app
  spec:

  ###########################################################################################################################################################################################
  # Configure EC2 instance security groups to permit the minimum required network traffic for the instance and only allow access from defined and expected locations (Do not allow 0.0.0.0/0)
  ###########################################################################################################################################################################################
  securityGroupSelectorTerms:
    # Select on any security group that has both the "karpenter.sh/discovery: ${CLUSTER_NAME}" tag
    # AND the "environment: test" tag OR any security group with the "my-security-group" name
    # OR any security group with ID "sg-063d7acfb4b06c82c"
    - tags:
        karpenter.sh/discovery: "muse-elevar-eks-dev"
        environment: test
    - name: my-security-group
    - id: sg-063d7acfb4b06c82c
  ###############################################################################################################
  # All file systems must be encrypted for data at rest to prevent unauthorized users from reading sensitive data
  ###############################################################################################################
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  detailedMonitoring: true
---
